#!/usr/bin/env python2.7
# -*- coding: UTF-8 -*-

import os
import fileinput
import sys
import time

#print("file://" + os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), "index.html"))

initialize_packet = '''
{
    "initialize": {
        "versionTypes": ["release", "nightly", ".developer"],
        "email": true,
        "applications": [
            {
                "name": "Paweł",
                "versions": {
                    "release": ["1.0"],
                    "nightly": ["1.0.1", "1.0.2"]
                }
            },
            {
                "name": "Wojciech",
                "versions": {
                    "release": ["1.0"],
                    "nightly": ["1.0.1", "1.0.2"],
                    "developer": ["Daniło"]
                }
            },
            {
                "name": "Konrad",
                "versions": {
                    "release": ["1.0"],
                    "nightly": ["1.0.1", "1.0.2"],
                    "developer": ["Gądek", "Madej"]
                }
            }
        ]
    }
}
'''

print(''.join(initialize_packet.splitlines())) # remove all newlines
sys.stdout.flush()

for line in fileinput.input("-"):
    if 'install' in line:
        for i in range(100):
            print("{{ \"download_progress\": {0} }}".format((i+1.0)/100.0))
            sys.stdout.flush()
            time.sleep(.030 if i > 0 else 2)
        for i in range(100):
            if i >= 58 and 'Gądek' in line:
                sys.stderr.write("Wild Shaman appears!\n")
                sys.stderr.flush()
                sys.exit(1)
                break
            elif i == 0 and 'Pietraszko' in line:
                print("{ \"message\": \"Na pewno się uda!\" }")
                sys.stdout.flush()
            elif i == 3 and 'Daniło' in line:
                print("Some unjson")
                sys.stdout.flush()
            elif i >= 6 and 'Madej' in line:
                sys.exit(0)

            print("{{ \"installation_progress\": {0} }}".format((i+1.0)/100.0))
            sys.stdout.flush()
            time.sleep(.015 if i > 0 else 2)
